Update main.sh
Fixxed incase if snapd didnt want to start because i got the error

"System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
error: cannot communicate with server: Post "http://localhost/v2/snaps": dial unix /run/snapd.socket: connect: no such file or directory"